### ISSUE TITLE
 {"code":-911,"msg":"invalid image"} error in ocr_test.go

### ISSUE THREAD

**Issue by bezzang-dev** [maengsanha/kakao-developers-api#22]
## Describe the bug
터미널에서 ocr_test.go 에서  json raw message를 스트링으로 변환하여 출력시키면
다음과 같은 에러 메시지가 출력됩니다. 

```sh
=== RUN   TestOCR
    ocr_test.go:18: {"code":-911,"msg":"invalid image"}
--- PASS: TestOCR (0.13s)
```

문제가 발생한 테스트 함수 입니다.

```go
func TestOCR(t *testing.T) {
	filepath := "/home/js/test6.jpeg"

	if or, err := vision.OCR(filepath).
		AuthorizeWith(common.REST_API_KEY).
		Collect(); err != nil {
		t.Error(err)
	} else {
		t.Log(or)
	}
}
```

## To Reproduce
1. Modify Code this
```go
} else {
		t.Log(or)
	}
```
to
```go
} else {
		t.Log(string(or))
	}
```
2. Open /kakao-developers-client/vision in terminal
3. Enter go test -v ocr_test.go

## Screenshot
![2022-02-26 23-31-22](https://user-images.githubusercontent.com/84405002/155847139-64defa5f-346e-43e1-9f03-109da7757a72.png)

**Comment by maengsanha** [comment]
Fixed.
You can check the solution [here](https://github.com/maengsanha/kakao-developers-client/commit/b1a886acf2a05019bfee177d9b9d9970257eb8f4)
