### ISSUE TITLE
{"code":-2,"msg":"image is not provided"} error in analyze_image and analyze_video

### ISSUE THREAD

**Issue by GoRyne** [maengsanha/kakao-developers-api#23]
카카오 REST_API 테스트 도구와 맥 터미널에서 curl 을 통해 요청을 할 땐 정상적인 결과값이 나오나 

- /pose/analyze_image_test.go 

```go
func TestAnalyzeImageWithFile(t *testing.T) {
	imagepath := "/Users/goryne/Downloads/testimage.jpg"

	if ir, err := pose.AnalyzeImage().
		WithFile(imagepath).
		AuthorizeWith(common.REST_API_KEY).
		Collect(); err != nil {
		t.Error(err)
	} else {
		t.Log(string(ir))
	}
}
```

해당 코드로 테스트를 진행시 아래와 같은 오류 메세지가 서버로 부터 날라옵니다.

```sh
{"code":-2,"msg":"image is not provided"}
```

video_search의 경우 카카오측에서 REST_API 테스트 도구를 제공하지 않아 정확한 비교를 할 순 없지만

```sh
{"code":-2,"msg":"video is not provided"}
```
오류가 나오는 것으로 보아 동일한 증상으로 보입니다.

## 스크린샷

<img width="2560" alt="스크린샷 2022-02-26 오후 11 01 54" src="https://user-images.githubusercontent.com/44722434/155846848-b8c477e9-6cb0-4638-9209-aa4e7792dfb3.png">

<img width="964" alt="스크린샷 2022-02-26 오후 11 23 13" src="https://user-images.githubusercontent.com/44722434/155846862-1c94104e-f06a-4a5b-baaa-4bd17cca6c5f.png">
위의 사진들 처럼 맥 터미널 curl 명령어와 카카오 REST_API 테스트 도구에선 정상적으로 통과 하나 

아래의 코드로 테스트 시
<img width="922" alt="스크린샷 2022-02-26 오후 11 05 27" src="https://user-images.githubusercontent.com/44722434/155846905-577da831-13bc-4831-9a38-c7e053e79ffa.png">

<img width="448" alt="스크린샷 2022-02-26 오후 11 04 59" src="https://user-images.githubusercontent.com/44722434/155846910-cbd7c07e-a83a-4565-9340-3eb199371b0f.png">

아래의 사진과 같은 오류 메세지가 서버로 부터 전송됩니다.
<img width="1009" alt="스크린샷 2022-02-26 오후 11 06 40" src="https://user-images.githubusercontent.com/44722434/155846930-a49c49a7-cc6b-48f5-8da7-570a8503d90d.png">

오류를 추적하다 맥 터미널에서 curl을 통하여 요청을 보낼때의 request content-length 와 소스 코드 중간에 
request의 content-length를 확인 해 보았을 때 서로 길이가 다름을 확인하였으나 정확한 원인을 찾진 못하였습니다

**Comment by maengsanha** [comment]
Same as vision. Resolved.
